# -*- coding: utf-8 -*-
"""dictionaries.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVXIIW3hzNKpizp365l9Xo67s6doGCb2

**Q # 01**
"""

no_of_products = eval(input("Enter Number of products: "))
my_dict ={}
for z in range(no_of_products):
    product_Name = input("Enter Product Name: ")
    product_Price = int(input("Enter Product Price in Rs: "))
    my_dict[product_Name] = product_Price


while True:
    product_Name = input("Enter Product name to get Price in Rs: ")
    if product_Name in my_dict:
        print("The price for your product is ", my_dict[product_Name])

    else:
        print("This product is not found in dictionary")
        print(my_dict)
        break

"""**Q # 2**"""

dollar =eval(input("Enter price of one dollar: $$"))
for key ,values in my_dict.items():
    if  int(values) < dollar:
        print (key ,"->",values)

"""**Q # 3**"""

#A
year = {"january":"31","Febuary" :"28", "March": "30","April" :"30","May":"31","June":"30","July":"30"}
month = input("enter name of a month: ")

for key, values in year.items(): 
  if month==key:
    print(values)

#B
year = {"january":"31","Febuary" :"28", "March": "30","April" :"30","May":"31","June":"30","July":"30"}
sorted_year = {key:year[key] for key in sorted(year)}
print(sorted_year.keys())

#C
year = {"january":"31","Febuary" :"28", "March": "30","April" :"30","May":"31","June":"30","July":"30"}
for keys, values in year.items():
  if int(values) == 31:
    print(keys)

#D
year = {"january":"31","Febuary" :"28", "March": "30","April" :"30","May":"31","June":"30","July":"30"}
user_input=input("enter name of month: ")
for key, values in year.items(): 
  if user_input in keys:
    print(values)

"""**Q # 4**"""

dic = {'CS02' : "11",
       'humam' : "22",
       'haseeb' : "33",
       'ibraheem' : "44",
       'waleed' : "55",
       'siraj' : "66",
       'shahab' : "77",
       'subhan' : "88",
       'rafay' : "99",
       'bilal' : "10" }

username = input("Enter username :- ")

if username in dic :
    password = input("Enter password :- ")
    if dic[username] == password :
        print ("You are now logged into the system.")
    else :
        print ("Invalid password.")
else :
    print ("You are not valid user.")

"""**Q # 5**"""

dic ={}
listwin = []
listrec = []
while True :
    name = input ("Enter the name of team (enter k for quit)= ")
    if name == "K" or name == "k" :
        print()
        break
    else :
        win = int (input("Enter the no.of win match = "))
        loss = int(input("Enter the no.of loss match = "))
        print()
        dic [ name ] = [ win , loss ]
        listwin += [ win ]
        if win > 0 :
            listrec += [ name ]

nam = input ("Enter the name of team For Winning = ")
print ("Winning percentage = ",dic [ nam ][0] *100 / (dic [nam ][0] + dic[nam ][1] ))
print()
print("Winning list of all team = ",listwin)
print("Team who has winning records are ",listrec)

"""**Q # 6**"""

def teamInfo():
   no_of_team =int(input("Enter Number Of Teams: "))
   team_dict={}
   for team in range(num_team):
       key = input("Enter Team name: ")
       value =[]
       wins = int(input("Enter Win: "))
       losses = int(input("Enter Losses: "))
       value.extend((wins,losses))
       team_dict.update({key:value})
       
   return team_dict

print(teamInfo())